name: gen-keystore
on:
  workflow_dispatch:
jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - name: Generate fixed debug keystore
        run: keytool -genkeypair -v -keystore debug.keystore -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=Android Debug,O=Android,C=US"
      - name: Print keystore base64 (chunked)
        run: |
          echo "BEGIN_KEYSTORE_B64"
          base64 debug.keystore | fold -w 200
          echo "END_KEYSTORE_B64"
